//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandogh.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> Activity { get; set; }
        public string UserPhone { get; set; }
        public byte[] UserImage { get; set; }
        public string CreateDate { get; set; }
        public int UsersJobID { get; set; }
    
        public virtual Tbl_Jobs Tbl_Jobs { get; set; }
    }
}
