//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandogh.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public int PersonID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Activity { get; set; }
        public byte[] UserImage { get; set; }
        public string CreateDate { get; set; }
        public int UsersJobID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Person Person { get; set; }
    }
}
